### PR TITLE
Solved 4 ISSUES: I have modified footer section, added css to the social media icons, formatted the nav-links in the header section, added apt css for welcome page , unnecessary message box below the form (above the footer) was removed.

### PR DESCRIPTION
**Pull request by JOSHITHA6**
I have added proper css for footer, social media icons, enabled the light-dark mode button and formatted the buttons for all navigation links present near the header.Also I removed unnecessary message box at the bottom, which was repeated twice , once in the form and the other below it. So, I removed the message box present below the form to avoid confusion. A total of 5 issues solved.

### Related Issue
Issue number: 524
Issue number: 545
Issue number: 513
Issue number: 555

### Description
For issue number 524: Updated the CSS of the footer section.
For issue number 545: Alignment of buttons in the home section have been made.
For issue number 513: Duplication of message box has been removed
For issue 555, I added a decent CSS to the header section to look elegant.

## Screenshots 📷
A) For ISSUE 524:
footer

B) For ISSUE 545:
added_buttons_canvas_gssoc

C)For ISSUE 513:
Screenshot (188)

D)For ISSUE 555:
Screenshot (186)

### Type of change
What sort of changes have you made:

I have modified the footer section, added CSS to the social media icons, formatted the nav-links in the header section, added apt CSS for the welcome page, and unnecessary message box below the form (above the footer) was removed.

### Checklist

- [x] My code follows the code style of this project.

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by JOSHITHA6** [comment]
> Please resolve merge conflicts

Okay after resolving merge issues its asking me to commit merge with 2 options 1)1) Commit updates to the main branch.2)Create a new branch and commit updates. Your pull request will be updated automatically. Which option shall I choose ?

**Comment by JOSHITHA6** [comment]
@vishanurag Completed resolving conflicts, kindly do check and please assign me as level-3 because I solved 4 issues so far

**Review by JOSHITHA6 — COMMENTED** [review]
Resolved merge conflicts.

**Comment by vishanurag** [comment]
I just tested your changes in codespaces and here is the result.


https://github.com/user-attachments/assets/dffd5c83-ac7d-4af8-8511-c9b8dada0bac


I'm rejecting your PR this time because it will make the entire project non-responsive also a lot of styling will be gone.

**Comment by vishanurag** [comment]
> But when I executed it these were not the results. They were the ones that I attached in the screenshots previously. I don't understand why it happened. A lot of efforts have gone unrecognized :-(
> 
> Let me try to resend my pr once again, if the same happens you can reject it. Please try to understand sir. Kindly give me an opportunity.

Ok

**Comment by JOSHITHA6** [comment]
https://github.com/user-attachments/assets/009a1cfe-7235-4d52-81f7-af14cf4a03a8


@vishanurag I have executed just now and here's the result. No styling has gone out of order. So, I will create a new pr and resend it to you.

**Comment by JOSHITHA6** [comment]
@vishanurag just check out pr no #1027. I have created a new pr and resent it
Thanks and regards.
Hopefully, it works this time as expected

**Pull request closed without merging**
