### PR TITLE
feat:Added footer section to different pages

### PR DESCRIPTION
**Pull request by likitha-kapu**
### Title of the Pull Request
- [X ] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #1229 

### Description

Added footer components to the different pages of the website

## Screenshots 📷

Screenshot 2024-11-09 222312

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [ X] My code follows the code style of this project.
- [ X] I have followed the contribution guidelines
- [ X] I have performed a self-review of my own code.
- [ X] I have ensured my changes don't generate any new warnings or errors.
- [ X] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts.

**Comment by likitha-kapu** [comment]
> Please resolve merge conflicts.

I am new to contributions I have no much knowledge of how to resolve it

**Comment by vishanurag** [comment]
> > Please resolve merge conflicts.
> 
> I am new to contributions I have no much knowledge of how to resolve it

Don't worry I have resolved the merge conflicts.

**Comment by likitha-kapu** [comment]
> > > Please resolve merge conflicts.
> > 
> > 
> > I am new to contributions I have no much knowledge of how to resolve it
> 
> Don't worry I have resolved the merge conflicts.

Thankyou so much

**Pull request merged**
