### PR TITLE
feat: Enhance button responsiveness and input field styles for better mobil…

### PR DESCRIPTION
**Pull request by Web-Dev-Learner**
Changes Made:

Improved responsiveness for the "Save" button and input field.
HTML: Ensured proper structure with Bootstrap classes for better alignment.
CSS Updates:
style.css: Added padding and styles for the input field and button.
responsive.css: Implemented media queries for mobile, ensuring full-width button and improved spacing.
Tested on various screen sizes to confirm functionality.

Screenshot 2024-10-01 231933

Screenshot 2024-10-01 231945

Screenshot 2024-10-01 232000

### CODE REVIEW

**Comment by vishanurag** [comment]
@Web-Dev-Learner please resolve the merge conflicts.

**Comment by vishanurag** [comment]
Also please mention your issue no.

**Comment by Web-Dev-Learner** [comment]
Pull Request #2 (Level 1, GSSoC-Ext) , Hacktoberfest.

I've successfully resolved the merge conflicts in the branch fix-savebutton-section.

Changes made:

Adjusted styles and responsiveness for the save button and input fields.
Merged with the latest changes from the main branch.

**Comment by vishanurag** [comment]
Ok

**Pull request merged**
