### PR TITLE
 Removed  duplicate icon and correct its position

### PR DESCRIPTION
**Pull request by samia-jucse**
### Title of the Pull Request
- [ ] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #<issue number>

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have followed the contribution guidelines
- [ ] I have performed a self-review of my own code.
- [ ] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [ ] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by samia-jucse** [comment]
I faced some problems to solve the conflict . Can you help me?

**Comment by samia-jucse** [comment]
@vishanurag please  check  the merge

**Comment by samia-jucse** [comment]
@vishanurag  please check this

**Comment by vishanurag** [comment]
There is a huge difference between the old Ui and new UI of this website. That's why I can't merge this PR.

**Pull request closed without merging**
