### PR TITLE
Added a FAQ section

### PR DESCRIPTION
**Pull request by rounakdey6**
i have solved the issue #128
image
please merge this issue Sir .
@vishanurag

### CODE REVIEW

**Comment by rounakdey6** [comment]
please merge this issue

**Comment by rounakdey6** [comment]
@vishanurag sir , please merge this issue

**Comment by rounakdey6** [comment]
I will resolve this conflict by today @vishanurag

**Comment by rounakdey6** [comment]
Sir Please check this

**Comment by rounakdey6** [comment]
solved the issue #252

**Comment by vishanurag** [comment]
Great

**Comment by rounakdey6** [comment]
@vishanurag can I be the collaborator of this project?
You can see my contribution in the contribution section

**Pull request merged**
