### PR TITLE
About us Re-designed

### PR DESCRIPTION
**Pull request by Son7c**
### Title of the Pull Request: About us page re-designed

Examples of good PR titles:

build:      (for build related changes)
chore:      (for updating task runner configs etc; no production code change)
docs:       (for documentation changes)
feat:       (for new feature)
fix:        (for bug fixes)
perf:       (for performance improvements)
refactor:   (for refactoring code; no production code change)
revert:     (when reverting changes)
style:      (changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc))
test:       (when adding missing tests)
-->

### Related Issue

Closes: #749 

## How Has This Been Tested? ⚙️

I had ran the code several times to check if there's any issue
## Screenshots 📷
https://github.com/user-attachments/assets/9e0fcbc0-9b27-4856-99b6-8d778f23b1cf

### Type of change
I have redesigned the entire about us page.

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Son7c** [comment]
@somyadipghosh Please review my PR.

**Review by somyadipghosh — APPROVED** [review]

**Comment by Son7c** [comment]
@somyadipghosh please merge it and tag level 3 as in issue it was tagged level 3

**Comment by somyadipghosh** [comment]
@Son7c given level3, wait for the PA, he'll merge it

**Comment by Son7c** [comment]
@vishanurag Please review this PR

**Comment by Son7c** [comment]
@vishanurag @somyadipghosh Please review this fast as i have to work on other sections of your website. hope you understand

**Comment by Son7c** [comment]
@somyadipghosh Please review this PR its been 2 days.

**Review by somyadipghosh — APPROVED** [review]

**Pull request merged**
