### PR TITLE
Home page elements fixed

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no. #733 

@somyadipghosh sir, i've fixed each and every element of the HOME page

**Before:**

https://github.com/user-attachments/assets/93548a00-1dc0-4584-86aa-b79095e0cb35

**After:**

https://github.com/user-attachments/assets/a238fa21-9ef2-45b2-984b-b5f7b87302c0

Changes done are:
1. Alignment fixed
2. Navbar UI enhanced
3. Language toggle ui improved
4. Title enhanced
5. Welcome section imrpoved

Screenshot 2024-10-20 232331

Screenshot 2024-10-20 235958

Screenshot 2024-10-21 000006

Kindly review once, let me know if any further adjustments are needed.

### CODE REVIEW

**Review by somyadipghosh — APPROVED** [review]

**Comment by NIKITABARANWAL890** [comment]
@somyadipghosh sir you assigned this issue at level 3, but now you've labelled it level2?
can you please assign it back to 3 as it required a lot time to fix the entire page.

and if all checks are approved kindly merge this PR as well

**Comment by NIKITABARANWAL890** [comment]
@vishanurag kindly review and merge this PR sir

**Comment by somyadipghosh** [comment]
@NIKITABARANWAL890  the PA might be busy, so kindly wait

**Comment by NIKITABARANWAL890** [comment]
@somyadipghosh sir, i've noticed that just because PRs are getting merged very late and because of that many contributors are raising issues for the same thing continously. This is leading to very slow improvement in Canvas-Editor website.

Kindly ask the PA to merge issues sooner as this will help alot of contributors to proceed further towards raising new issues which can actually create a difference towards Canvas-Editor's page development.

I hope you'll surely look into it?

**Comment by NIKITABARANWAL890** [comment]
@vishanurag sir kindly merge this PR

**Comment by NIKITABARANWAL890** [comment]
@vishanurag Sir, as contributors, we understand that you have a lot of work to manage. However, when PRs remain unmerged for 5-6 days, it can lower our motivation to continue contributing. We humbly request that you kindly review and merge our PRs at your earliest convenience.

Thank you,

**Comment by NIKITABARANWAL890** [comment]
@somyadipghosh i've seen you merging PR's of other contributors but none of my PR is being merged by you, can you please do that?

**Review by somyadipghosh — APPROVED** [review]

**Pull request merged**
