### PR TITLE
added darkmode ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### Title of the Pull Request
issue #265 

the darkmode is working ! @vishanurag can you please review this code , thank you!

https://github.com/user-attachments/assets/67c35e2a-97c7-4614-893a-b1ea461fead0

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [X] My code follows the code style of this project.
- [X] I have followed the contribution guidelines
- [X] I have performed a self-review of my own code.
- [X] I have ensured my changes don't generate any new warnings or errors.
- [X] I have updated the documentation (if necessary).
- [X] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag can you please review this PR.
thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag can you please review this PR.
thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag can you please review this PR.
thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag can you please review this PR.
thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag can you please review this PR. is has been 3 days.
thank you.

**Comment by T-Rahul-prabhu-38** [comment]
please review this @vishanurag , i made this long back.

**Comment by vishanurag** [comment]
Resolve merge conflicts

**Comment by T-Rahul-prabhu-38** [comment]
one sec

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag done!

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag done!
 can you please review this , thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag done!
can you please review this , thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag done!
can you please review this , thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag done!
can you please review this PR ,i have one more to make,
thank you

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag done!
can you please review this PR ,i have one more to make,
thank you

**Comment by vishanurag** [comment]
Since, dark mode is already there in this website. I will be rejecting your PR this time.

**Comment by T-Rahul-prabhu-38** [comment]
@vishanurag bhai i did it one week ago , and i was assigned this issue.
how can you reject this now

**Pull request closed without merging**
