### PR TITLE
Enhancing web page

### LINKED ISSUE #3: Enhancing web page
I want to make the  webpage more user friendly , by adding  css  styles and including  web page responsiveness . please assign this issue to me  as gssoc-ext contributor  with appropriate level .

### PR DESCRIPTION
**Pull request by Pranshu-jais**
Fixes #3 

made webpage user friendly and added functionality to the buttons 

Screenshot 2024-10-03 195419

https://github.com/user-attachments/assets/b91b0ae9-cee4-4ace-ab5c-dbdbfa41bb21

### CODE REVIEW

**Comment by vishanurag** [comment]
Resolve the merge conflicts

**Comment by Pranshu-jais** [comment]
@vishanurag  i have resolved the conflict

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by Pranshu-jais** [comment]
> Please mention your issue no.

my issue no . is #3

**Pull request merged**
