### PR TITLE
Made the About us page functional and maintained the same navbar all across the pages.

### LINKED ISSUE #1125: 🧑‍💻: Other pages do not support similar UI and Navbar
### Title

The About us, review, testimonial, privacy, tutorial, blog andfeedback page do not all contain the same navbar and the same Canvas Editor icon. When these pages are viewed one after the other all of them seem to be leading to another website which looks uncanny and unorganised overall.

### Enhancement Aim

Let each page in indivisual have the same navbar navigating to the right pages instead of multiple differnet page designs

### Changes

change of colour scheme and navbar in each of the pages. change in the navigating part in each of the pages.

### Screenshots 📷

Screenshot 2024-10-31 172249
Screenshot 2024-10-31 172303
Screenshot 2024-10-31 172325
Screenshot 2024-10-31 172340
Screenshot 2024-10-31 172414
Screenshot 2024-10-31 172359
Screenshot 2024-10-31 172428
Screenshot 2024-10-31 172441

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Sania Golhar

### Participant Role

GSSOC-EXT 2024, Hachtoberfest

### PR DESCRIPTION
**Pull request by sania-2912**
All pages support same navbar and ui

Resolved the functionality of about-us page

Fixes #1125
Fixes #1136

 Have you renamed the PR Title in a meaningful way?
Pages changed:
-Index
About us
review
testimonial
privacy
tutorial
blog
FAQ
contributers
Related Issue
Closes: https://github.com/vishanurag/Canvas-Editor/issues/1125

Description
Changed the UI of pages and aligned all of them with the same NAVBAR which liks to the same pages as and when clicked. Also removed sign in, sign-up buttons on other pages and the extra login page button on the home page.

Screenshots 📷
Screenshot 2024-11-02 180420
Screenshot 2024-11-02 180452
Screenshot 2024-11-02 180500
Screenshot 2024-11-02 180518
Screenshot 2024-11-02 180533
Screenshot 2024-11-02 180541
Screenshot 2024-11-02 180444

Type of change
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)

Checklist
 My code follows the code style of this project.
 I have followed the contribution guidelines
 I have performed a self-review of my own code.
 I have ensured my changes don't generate any new warnings or errors.
 I have updated the documentation (if necessary).
 I have resolved all merge conflicts.

I hope the contribution mase is substancial!

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by sania-2912** [comment]
@vishanurag what seems to be the merge-conflict issue?

**Comment by sania-2912** [comment]
@vishanurag resolved

**Review by sania-2912 — COMMENTED** [review]
I have removed the merge-conflict. @vishanurag kindly check

**Pull request merged**
