### PR TITLE
Fixes the issues raised in  FAQ's section

### PR DESCRIPTION
**Pull request by rupeshv2121**
Now form empty submission issue is resolved.
Hover effect on the social media icon resolved.

Issue Number : #1172 

@vishanurag pls review the code and merge it.
pls add label gssoc-ext, hactoberfest-accepted.

### CODE REVIEW

**Comment by rupeshv2121** [comment]
@vishanurag sir pls merge my PR

**Comment by rupeshv2121** [comment]
sir pls tell them to merge that @MastanSayyad

**Comment by vishanurag** [comment]
Please resolve merge conflicts.

**Comment by vishanurag** [comment]
image

image

There are lot of errors in this PR.

**Comment by rupeshv2121** [comment]
@vishanurag can i create PR again

**Comment by rupeshv2121** [comment]
this happens due to github bot

**Pull request closed without merging**
