### PR TITLE
 🧑‍💻: Dynamic copyright section #1076 

### PR DESCRIPTION
**Pull request by AE-Hertz**
### Title of the Pull Request
- [X] Have you renamed the PR Title in a meaningful way?

 🧑‍💻: Dynamic copyright section #1076 

### Related Issue

Closes: #1076 

### Description

 automated the copyright section 

## How Has This Been Tested? ⚙️

yes i have tested locally.

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [X] My code follows the code style of this project.
- [X] I have followed the contribution guidelines
- [X] I have performed a self-review of my own code.
- [X] I have ensured my changes don't generate any new warnings or errors.
- [X] I have updated the documentation (if necessary).
- [X] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by AE-Hertz** [comment]
@vishanurag hey, i dont know why their is merge conflict even happeing after resolving it,can you check once.

**Comment by AE-Hertz** [comment]
@vishanurag check if you can merge latest changes.

**Comment by vishanurag** [comment]
> @vishanurag hey, i dont know why their is merge conflict even happeing after resolving it,can you check once.

Don't worry I have resolved the merge conflicts for you.

**Review by vishanurag — APPROVED** [review]

**Pull request merged**
