### PR TITLE
Add a Translation Tool done ! #778

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add Translation tool - #778 

Done -

https://github.com/user-attachments/assets/2ab264ed-c7ec-46ae-8ed9-90c75ea2fc37

Screenshot 2024-10-21 013734

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Review by somyadipghosh — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
@somyadipghosh Please merge my PR with Level 3, You gave me level 3 when you assigned me...

Screenshot 2024-10-21 131359

If you check other projects, they are giving level 3 for this -

Screenshot 2024-10-19 130956



Thank You 🙏🏻

**Comment by somyadipghosh** [comment]
@Subhajit-2023-44 the PA will merge it

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 the PA will merge it

@somyadipghosh please merge my PR, otherwise i can't st another work

**Review by somyadipghosh — APPROVED** [review]

**Comment by somyadipghosh** [comment]
@Subhajit-2023-44 you can start working now

**Pull request merged**
