### PR TITLE
#962

### PR DESCRIPTION
**Pull request by muskan-fatim**
### improve uI desgin
- [x] Have you renamed the PR Title in a meaningful way?
  - **PR Title**: `feat: Add hover effects, update contact us, and change message color`

### Related Issue
#962 

### Description
- Added a hover effect on links to improve user interactivity.
- Updated the "Contact Us" section for better visual appeal.
- Changed the color of the message area to align with the overall design and make it stand out.

These changes enhance the user experience by providing more interactive and visually appealing UI elements.

## How Has This Been Tested? ⚙️
- Manually tested the hover effects on links to ensure they display correctly.
- Verified that the "Contact Us" section updates appear as intended.
- Confirmed that the message color change does not conflict with the project’s style.

## Screenshots 📷
image

capture1

### Type of change
What sort of changes have you made:
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)

### Checklist
- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines.
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).

---

This format should give the reviewers all the information they need to understand and assess your contribution. Good luck with your pull request!

### CODE REVIEW

**Comment by vishanurag** [comment]
resolve merge conflicts

**Comment by muskan-fatim** [comment]
Okay I will fix the conflict

**Review by muskan-fatim — COMMENTED** [review]
Try to resolve conflict

**Review by muskan-fatim — COMMENTED** [review]
update

**Pull request merged**
