### PR TITLE
feat(font-button): Created a font button for bold, italics, uppercase…

### LINKED ISSUE #134: Enhanced Text & Shape Customization Tool
Enhance the text editing and drawing tool by adding separate sections for font selection and shape drawing. This will provide users with a clear and intuitive interface, allowing them to easily customize text styles and draw shapes without confusion. The updated design will improve user experience and accessibility, making the tool more effective for quick projects and casual use.

### PR DESCRIPTION
**Pull request by Bhoomysingh10**
Fixes #134

…, lowercase

This change focuses on enhancing the text editing by adding separate button for font selection which when clicked on opens an arc shaped sidebar.

## Screenshot of the change
image

### CODE REVIEW

**Comment by Bhoomysingh10** [comment]
Hey!! @vishanurag Ready for review :)

**Comment by Bhoomysingh10** [comment]
Hey! @vishanurag Ready for Review :)

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by Bhoomysingh10** [comment]
@vishanurag ,my issue number is #134

**Pull request merged**
