### PR TITLE
change in css , changed font size for better visibility in style.css

### LINKED ISSUE #712: Font size should be better.
It would be helpful to have better control over the font size for improved readability and design consistency.

### PR DESCRIPTION
**Pull request by NirajD04**
Fixes #712

### Title of the Pull Request
- [ ] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #<issue number>

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have followed the contribution guidelines
- [ ] I have performed a self-review of my own code.
- [ ] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [ ] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by NirajD04** [comment]
@vishanurag I only change some font size, please consider  this.

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by NirajD04** [comment]
@vishanurag 712.

**Comment by NirajD04** [comment]
could you assign me any other task also really wanted to contribute

**Pull request merged**
