### PR TITLE
changed the footer section in neat way

### PR DESCRIPTION
**Pull request by monishkumardvs**
image
 changed the footer section .

### CODE REVIEW

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by monishkumardvs** [comment]
#173

**Comment by monishkumardvs** [comment]
> Please mention your issue no.

#173

**Comment by vishanurag** [comment]
> > Please mention your issue no.
> 
> #173

#173 is your pr no. not issue no.

Please mention your issue no.

**Comment by monishkumardvs** [comment]
#158

**Comment by monishkumardvs** [comment]
> > > Please mention your issue no.
> > 
> > 
> > #173
> 
> #173 is your pr no. not issue no.
> 
> Please mention your issue no.

 #158

**Comment by vishanurag** [comment]
Resolve merge conflicts

**Pull request merged**
