### PR TITLE
✨Add Visitor Counter feature done ! #985

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #985
Add Visitor Counter feature done properly - 

Screenshot 2024-10-28 163440

before - 

Screenshot 2024-10-28 163449

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishanurag done, please merge my PR with level 3,

Thank You

**Review by vishanurag — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
@vishanurag Sir kindly 🙏🏻 upgrade the level 2 to 3, If you check other projects, they are also giving level 3 for this.. You can check my code also...

Screenshot 2024-10-22 204511

Thank You

**Comment by Subhajit-2023-44** [comment]
@vishanurag Sir kindly 🙏🏻 upgrade the level 2 to 3..

**Comment by Subhajit-2023-44** [comment]
@vishanurag Sir kindly 🙏🏻 upgrade the level 2 to 3..

**Pull request merged**
