### PR TITLE
feat: added the capitalise , small , bold and italic buttons to edit the text

### PR DESCRIPTION
**Pull request by adityalaxkar123**
Fixes: #5 

# added the capitalise , small , bold and italic buttons to edit the text.

### add downlaod btn for downloading the edited text in  the pdf format.

### CODE REVIEW

**Comment by vishanurag** [comment]
@netlify /

**Comment by vishanurag** [comment]
Please provide the issue no.

**Comment by vishanurag** [comment]
@netlify /

**Comment by vishanurag** [comment]
@netlify

**Comment by vishanurag** [comment]
There is some issue with netlify deployment bot. Don't worry,I will merge your pr as soon as possible.

**Comment by adityalaxkar123** [comment]
Is their any problem from my side

**Comment by vishanurag** [comment]
No problem

**Comment by vishanurag** [comment]
I am merging your PR. Awesome work done by you 👍

**Pull request merged**
