### PR TITLE
Button Styles added

### PR DESCRIPTION
**Pull request by Poushmita**
### Title of the Pull Request
- [X] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #36 

### Description

The style of the buttons have been changed for better user-experience

### BEFORE Hover Effect
p2

### AFTER Hover Effect
- FIRST SET OF BUTTONS
 p1

- SECOND SET OF BUTTONS
p3

- THIRD SET OF BUTTONS
p4

- FOURTH SET OF BUTTONS
p5

### Type of change
What sort of changes have you made:

- [X] New feature (non-breaking change which adds functionality)

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Poushmita** [comment]
@vishanurag please check my PR request and let me know if any change is needed.

**Comment by Poushmita** [comment]
@vishanurag  please merge my PR

**Comment by Poushmita** [comment]
@vishanurag please check my PR request and let me know if any change is needed.

**Comment by Poushmita** [comment]
@vishanurag merge my PR

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by Poushmita** [comment]
@vishanurag please check now

**Pull request merged**
