### PR TITLE
Fixed the CONTACT US overflowing contents also changed the UI of canvas

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
Fixed the CONTACT US overflowing contents
(BEFORE)
Screenshot 2024-10-10 210835

(AFTER)
Screenshot 2024-10-10 211857

ALSO changed the CANVAS BOX SIZE equal to the elements size
 (BEFORE)
Screenshot 2024-10-10 215352

(AFTER)
Screenshot 2024-10-10 221059

### Title of the Pull Request
- [ ] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #<issue number>

### Type of change
What sort of changes have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have followed the contribution guidelines
- [ ] I have performed a self-review of my own code.
- [ ] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [ ] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@vishanurag Please review my pull request and merge it. Also, Don't Forget to assign labels to it

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by PatelHarsh2006** [comment]
Sorry, Not issued yet issued ( bcz in other Open Source Projects they see Pull request (first issuing is not compulsory) only )

**Comment by vishanurag** [comment]
Ok I'm merging your PR. But Your issue need to be assigned first then your pr can be merged. This is a good practice.
Remember this from next time.

**Comment by PatelHarsh2006** [comment]
> Ok I'm merging your PR. But Your issue need to be assigned first then your pr can be merged. This is a good practice. Remember this from next time.

Thank You for Merging my Request

**Pull request merged**
