### PR TITLE
Update index.html

### LINKED ISSUE #146: Proposal for Correction of Button Text Formatting
I have observed that the button labels in our application currently use unconventional formatting styles, specifically "AUpper," "aLower," "BBold," and "IItalic." This inconsistency not only affects the aesthetic appeal but may also confuse users. I propose a standardization of the button text formatting to enhance usability and maintain a professional appearance.

I would like to work on this issue if you assign it to me.
Thanking you.
Screenshot 2024-10-05 120429

### PR DESCRIPTION
**Pull request by AyushiTaralkar**
Fixes #146 

<br>

onsistent Labeling: Clear and uniform button labels.
Enhanced Usability: Easier for users to understand button functions.
Improved Aesthetics: A more professional and polished look.
Better Accessibility: Easier identification and use for all users.
Easier Maintenance: Simplified updates and modifications in the future.
Increased User Satisfaction: Higher likelihood of user engagement and retention.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by AyushiTaralkar** [comment]
#146

**Comment by AyushiTaralkar** [comment]
this is the issue number

**Comment by AyushiTaralkar** [comment]
Thank you.

**Comment by vishanurag** [comment]
Your welcome 😁

**Pull request merged**
