### PR TITLE
Dark mode toggle improved

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no.#791

@somyadipghosh i've changed the color theme for dark mode as well with the website's theme.

https://github.com/user-attachments/assets/16ad2bc1-59c5-4786-85cb-58cfbea4fcff

kindly review once, and let me know if any further adjustments are needed.

### CODE REVIEW

**Comment by somyadipghosh** [comment]
@NIKITABARANWAL890 kindly check which level i've assigned you this issue

**Comment by NIKITABARANWAL890** [comment]
@vishanurag kindly review and merge this PR sir

**Comment by somyadipghosh** [comment]
@NIKITABARANWAL890 wait for the PA, he'll review and merge it

**Comment by NIKITABARANWAL890** [comment]
@vishanurag sir it's been so long that you merged any PR of mine, kindly merge all the PRs and don't let my motivation down regarding further contributions, it's an humble request.

**Review by vishanurag — APPROVED** [review]

**Pull request merged**
