### PR TITLE
Fixed Your Message in homepage

### PR DESCRIPTION
**Pull request by AsifQamar**
@somyadipghosh please review and merge it
Screenshot_353

### CODE REVIEW

**Comment by AsifQamar** [comment]
@somyadipghosh @vishanurag please review and merge

**Review by somyadipghosh — APPROVED** [review]

**Comment by AsifQamar** [comment]
@somyadipghosh assign the tags

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Review by MastanSayyad — COMMENTED** [review]
No significant change, only few css adjustments @vishanurag @somyadipghosh  any reason you gave level 3 to this? have you reviewed the code before?

**Comment by vishanurag** [comment]
> No significant change, only few css adjustments @vishanurag @somyadipghosh any reason you gave level 3 to this? have you reviewed the code before?

@MastanSayyad this might be done via some mistake by @somyadipghosh

**Comment by MastanSayyad** [comment]
@vishanurag No problem

**Comment by AsifQamar** [comment]
> > No significant change, only few css adjustments @vishanurag @somyadipghosh any reason you gave level 3 to this? have you reviewed the code before?
> 
> @MastanSayyad this might be done via some mistake by @somyadipghosh

Can u give it level 1

**Pull request merged**
