### PR TITLE
feat: Added uniform navbar  across all pages of the website.

### PR DESCRIPTION
**Pull request by Palmistry2310**
### Title of the Pull Request
- [x] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #455 #456 #464

### Description
Create a responsive navbar from the scratch and added it to all the 8 pages(,about,blog,signup etc etc ) of the website making it look uniform and consistent.

## Screenshots 📷

https://github.com/user-attachments/assets/24a1c548-20d4-4d09-a811-3578e92bcb31

### Type of change
What sort of changes have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

@vishanurag PLease review this pr!

### CODE REVIEW

**Comment by Palmistry2310** [comment]
@vishanurag Please have a look at this PR! I have resolved the merge conflicts.

**Comment by Palmistry2310** [comment]
@vishanurag please provide some updates and let me know!!

**Comment by Palmistry2310** [comment]
@vishanurag please review this pr and if u dont want changes to be added, then please close it. Please dont leave it like this providing no updates.

**Comment by Palmistry2310** [comment]
@somyadipghosh please review this pr!

**Review by somyadipghosh — APPROVED** [review]

**Pull request merged**
