### PR TITLE
Welcome page and added some functionalities.

### PR DESCRIPTION
**Pull request by JahnavikaGopalbvrith**
welcome page 
add text ,text color ,font style, font color ,undo and redo, brush size and other functionalities as well #137

### CODE REVIEW

**Comment by JahnavikaGopalbvrith** [comment]
Any changes please let me know?

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by JahnavikaGopalbvrith** [comment]
Ok

**Comment by JahnavikaGopalbvrith** [comment]
please add these level , gssoc-ext, hacktoberfest-accepted labels

**Pull request merged**
