### PR TITLE
Add a User Profiles page done ! #1143

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #1143
Add a normal user profile page and a profile icon in the home page that redirects to the profile page done -

Screenshot 2024-11-03 192202
Screenshot 2024-11-03 192210

https://github.com/user-attachments/assets/60d75c99-afa0-45b4-b7d3-276824713368

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishanurag done, Sir merge my PR & please give me **level 3**, 

**you can check my code i have added a lot and also i add this new feature** 👀✨

image

Thank You, I hope you give me level 3 for this.. 🙏🏻🌟

If you check other projects, they also give level 3 for this...

Screenshot 2024-11-03 001321
Screenshot 2024-11-02 230302
Screenshot 2024-11-03 121147

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir please merge my PR with level 3 & gssoc-ext label

**Comment by vishanurag** [comment]
Please resolve merge conflicts.

**Comment by Subhajit-2023-44** [comment]
> Please resolve merge conflicts.

@vishanurag sir done, please merge my PR with level 3 & gssoc-ext label

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir please upgrade the level 2 to 3, you can check my code i have added a lot and also i add this new feature 👀✨

Screenshot 2024-11-07 190856

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir please upgrade the level 2 to 3,

**Pull request merged**
