### PR TITLE
Updated features of home page with new logo, navigation bar,  more 

### PR DESCRIPTION
**Pull request by ParulPrashar**
section links, styled buttons, color pattern, alignment. The conflicts are not due to major changes but just that i have changed the previous button size and added colors and fonts to them.

Screenshot (1)
Screenshot (3)

### CODE REVIEW

**Comment by vishanurag** [comment]
Resolve the merge conflicts

**Comment by ParulPrashar** [comment]
@vishanurag sir can you guide on how to do this part.

**Comment by ParulPrashar** [comment]
@vishanurag Sir resolved the merge conflicts

**Comment by Ananya-vastare** [comment]
I would Like to solve this problem I am gssoc contributor

**Comment by adarshsingh0103** [comment]
@ParulPrashar  Can you please! assign me to work on this issue.

**Pull request closed without merging**
