### PR TITLE
Add Dark theme at home page

### PR DESCRIPTION
**Pull request by ishivansmishra**
#791 Solved

### Description
I added Dark mode Toogle that enhance or add the dark mode theme in the home page.

## Screenshots 📷

https://github.com/user-attachments/assets/3da50387-ef3d-4671-a3bb-a5d72db53845

### CODE REVIEW

**Comment by ishivansmishra** [comment]
@somyadipghosh I submit the PR please check it and merge it under Gssoc-ext and hactoberfest label and give me level-3

**Comment by ishivansmishra** [comment]
@vishanurag kindly please check my PR and merge it...

**Comment by ishivansmishra** [comment]
@vishanurag Please check the PR and accept it

**Comment by ishivansmishra** [comment]
@somyadipghosh Please Check my PR and merge it.

**Review by somyadipghosh — APPROVED** [review]

**Pull request merged**
