### PR TITLE
Issue #26 UPDATE

### PR DESCRIPTION
**Pull request by Sagar2006**
## UI Changes
- Add a new "Add Text" button next to the existing controls
- Consider renaming the "Save" button to "Update" for clarity

## Benefits
- Users can create more complex designs with multiple text elements
- Increased flexibility and functionality of the text editor
- Improved user experience for creating diverse canvas designs

## Potential Challenges
- Ensuring smooth performance with multiple text elements
- Implementing an intuitive selection mechanism for editing specific text elements
- Updating the undo/redo functionality to work with multiple elements

## Additional Considerations
- We may need to update the drag functionality to work with individual text elements
- The capitalize/lowercase buttons should apply to the selected text element
- Consider adding a way to delete individual text elements

## Next Steps
1. Discuss the proposed changes with the team
2. Create a new branch for this feature
3. Implement the changes and test thoroughly
4. Update documentation to reflect the new functionality
5. Create a pull request for review

Please comment with any suggestions or concerns about this proposed feature.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve the merge conflicts

**Comment by Sagar2006** [comment]
please check now.

**Comment by Sagar2006** [comment]
it is still showing can you give me the permission to edit this

**Comment by Sagar2006** [comment]
As we need to change
"<<<<<<< main
</html>
=======
</html>
>>>>>>> main"

to 

</html>
but i am unable to save the changes maybe i don't have permission to edit that

**Comment by Sagar2006** [comment]
sir i have created another pull request with no branch conflicts

**Pull request closed without merging**
