### PR TITLE
feat: Redesigning of the testimonial page(#771)

### LINKED ISSUE #771: Redesigning of testimonial page
Description:
The current testimonial page may not fully leverage modern design practices. A redesign will make the page more visually appealing and user-friendly, ultimately leading to better user engagement and satisfaction.

kindly assign it to me under gssoc'24 ext

### PR DESCRIPTION
**Pull request by Subashree-selvaraj**
### Title of the Pull Request
- [X]  Have you renamed the PR Title in a meaningful way?

### Related Issue
Closes: #771 

Fixes #771 
### Description:
This PR  with newly designed testinomial page makes this website more visually appealing

### Before:
Screenshot 2024-11-02 140931

### After:

https://github.com/user-attachments/assets/0e611f44-f3d2-405b-8294-03037f4d0931

### Type of change
What sort of changes have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:
- [X] My code follows the code style of this project.
- [X] I have followed the contribution guidelines
- [X]  I have performed a self-review of my own code.
- [X]  I have ensured my changes don't generate any new warnings or errors.
- [X]  I have updated the documentation (if necessary).
- [X]  I have resolved all merge conflicts.

### CODE REVIEW

**Comment by rishika105** [comment]
Hey. I think your title is not according to the format. Write like "feat: your title with issue number". In that way all checks must be successful. Then only it can be merged.

**Comment by Subashree-selvaraj** [comment]
@vishanurag Kindly review this PR

**Review by vishanurag — APPROVED** [review]

**Comment by Subashree-selvaraj** [comment]
Sir actually level label is level3

**Comment by Subashree-selvaraj** [comment]
Ok sir thankyou

**Pull request merged**
