### PR TITLE
Contributors page redesigned

### PR DESCRIPTION
**Pull request by Son7c**
###feat
- [x] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #1197 

### Description
Changed the entire contributors page.

## How Has This Been Tested? ⚙️

I have self review this code many times.

## Screenshots 📷
Before
Screenshot 2024-11-08 141913

After

https://github.com/user-attachments/assets/4fe972e2-5003-4102-89d6-ff83e25505f4

### Type of change
Styling change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Son7c** [comment]
@vishanurag @somyadipghosh Please merge this PR with level3 tag thank you.

**Comment by Son7c** [comment]
@vishanurag @somyadipghosh Please merge this PR as I need the points for the leaderboard. I completed my work as promised.

**Comment by vishanurag** [comment]
Please resolve merge conflicts.

**Comment by vishanurag** [comment]
image

I can't merge this PR because the footer is not looking good now, also the pagination feature of this page is gone...

**Comment by Son7c** [comment]
Ok close this PR

**Comment by Son7c** [comment]
@vishanurag must be some glitch I'll create a new PR fixing the glitches

**Comment by Son7c** [comment]
@vishanurag I rechecked my code 10-15 times and its perfectly fine but in deploy its showingdifferent.

**Comment by vishanurag** [comment]
You should create a new pr rather.

**Pull request closed without merging**
