### PR TITLE
Added dragging visibility for all shapes

### PR DESCRIPTION
**Pull request by swathivemula7**
### Related Issue

Closes: #1056 

### Description
This PR enhances the canvas drawing tool by enabling visible feedback during dragging actions. Previously, only finalized shapes and lines were visible after releasing the mouse, making it difficult for users to position and size shapes accurately while dragging. With this update, users can see shapes, lines elements in real-time as they draw.

## Screenshots 📷

https://github.com/user-attachments/assets/0544018d-bffd-41c4-b31d-c0a9faa597d6

https://github.com/user-attachments/assets/3aa860ab-0942-4fce-a0db-f095be22ed93

@vishanurag @somyadipghosh Kindly review the PR at the earliest..
I have mentioned only Rectangle dragging visibilty in the issue #1056, but have implemented this feature for all the shapes in canvas editor..Consider upgrading the level..

Note: Some changes in the code are due to pulling the origin...

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by swathivemula7** [comment]
@vishanurag resolved the conflicts

**Comment by swathivemula7** [comment]
@vishanurag also the main canvas editor website is showing as dangerous by Google safe...please check

**Comment by swathivemula7** [comment]
@vishanurag @somyadipghosh Please review the PR at the earliest

**Review by vishanurag — APPROVED** [review]
Awesome Work 👍

**Comment by swathivemula7** [comment]
@vishanurag Kindly consider upgrading to level3

**Pull request merged**
