### PR TITLE
Responsive Design: Improved Button and Text Box Sizes with Custom Hover Effects

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
Major Changes made : 
->   Added hover effects for these buttons where their names (Bold, Italic, Uppercase, Lowercase) appear on 
       hover.
->  Color Update: Applied distinct colors—green for Save, red for Clear, and blue for Download.
Screenshot (1022)

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts and also mention your issue no. in this PR.

**Comment by AnujShrivastava01** [comment]
I have resolved the conflict .
Please check and merge pull request .
Also please give my level3 label here in pull request section for points evaluation.
Thnakyou!

**Comment by vishanurag** [comment]
Please mention your issue no also

**Comment by AnujShrivastava01** [comment]
> Please mention your issue no also

#18  

image

**Pull request merged**
