### PR TITLE
Add a pop up dialog box for subscribing to newsletter done ! #929

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #929
Add a pop up dialog box for subscribing to newsletter done properly -

Screenshot 2024-10-27 171132

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishanurag @somyadipghosh  done, Sir please merge my PR with level 3, If you check other projects, they are also giving level 3 for this..

Screenshot 2024-10-26 112803

You can check my code..

Thank you 🙏🏻

**Comment by vishanurag** [comment]
resolve merge conflicts

**Comment by Subhajit-2023-44** [comment]
> @vishanurag @somyadipghosh done, Sir please merge my PR with level 3,

@vishanurag done, Sir please merge my PR with level 3,

**Comment by Subhajit-2023-44** [comment]
@vishanurag Sir kindly 🙏🏻 upgrade the level 2 to 3, If you check other projects, they are also giving level 3 for this.. You can check my code also...

Screenshot 2024-10-28 134944
Screenshot 2024-10-28 135037

**Comment by Subhajit-2023-44** [comment]
@vishanurag Thank You sir 🙏🏻

**Pull request merged**
