### PR TITLE
Add a ChatBot Assistant done ! #827

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new Feature - #827

Add a ChatBot Assistant done -

https://github.com/user-attachments/assets/19a3e3c0-a7ed-41ec-ad04-145ba62842fe

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@somyadipghosh Done ✅

Please merge my PR with Level 3, 

Screenshot 2024-10-24 233536


Thank You 🙏🏻

**Comment by vishanurag** [comment]
There is already a chat bot present in the website

**Comment by Subhajit-2023-44** [comment]
> There is already a chat bot present in the website

@vishanurag Sir please check this - #827

**Comment by Subhajit-2023-44** [comment]
@vishanurag @somyadipghosh

**Comment by Subhajit-2023-44** [comment]
@vishanurag @somyadipghosh please merge my PR, otherwise i can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
@vishanurag @somyadipghosh please merge my PR, otherwise i can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
> > There is already a chat bot present in the website
> 
> @vishanurag Sir please check this - #827
> 
> and merge my PR with label, Thank You

@vishanurag @somyadipghosh please merge my PR, otherwise i can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
@vishanurag

**Pull request closed without merging**
