### PR TITLE
Navbar Redesign: Updated Palette and Aligned Elements

### PR DESCRIPTION
**Pull request by govindbairi**
### Title of the Pull Request
Navbar Redesign: Updated Palette and Aligned Elements
#857 
- [X] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #857 

### Description
Updated the navbar with a new color palette, improved hover effects, and modern fonts/icons.
Aligned elements for better spacing and balanced positioning, enhancing overall structure.
Enhanced responsiveness and accessibility, ensuring smooth transitions and better usability across devices.

## Screenshots 📷

Before

https://github.com/user-attachments/assets/633eb9e9-1c0b-4d29-8d06-47574191e69b

After

https://github.com/user-attachments/assets/6f8d52b2-22dc-438d-b7c8-8f4dbe5a45b3

### Type of change
Updated Color Palette:

Changed the colors of the navbar to match a new design scheme or brand identity.
Adjusted the background color, text color, hover effects, and active state colors.
Implemented a gradient or solid fill that complements the overall page theme.
Element Alignment:

Improved the alignment of the navigation items (e.g., left-aligned, center-aligned, or evenly spaced).
Adjusted the positioning of the logo, menu items, and other elements like buttons or icons to ensure they are aligned properly.
Made adjustments for better spacing and padding between elements, ensuring a consistent look.
Responsive Design Adjustments:

Modified the navbar's layout for better responsiveness on different screen sizes (e.g., mobile, tablet, desktop).
Added or improved a dropdown or hamburger menu for mobile view.
Enhanced the layout's fluidity to adapt to changes in screen width without breaking the design.
Font and Icon Updates:

Changed the fonts used in the navbar to match the new design style.
Updated or added icons for navigation items, ensuring they align with the updated style.
Accessibility Enhancements:

Improved the contrast ratio of the text against the navbar background for better readability.
Added ARIA labels or other semantic HTML elements for better screen reader compatibility.
Ensured that the navbar is fully navigable with keyboard controls.
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### Checklist

- [X] My code follows the code style of this project.
- [X] I have followed the contribution guidelines
- [X] I have performed a self-review of my own code.
- [X] I have ensured my changes don't generate any new warnings or errors.
- [X] I have updated the documentation (if necessary).
- [X] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by govindbairi** [comment]
kindly review my code
Requesting to add a Level 3 label to my PR focused on Updated Palette or redesigned and Aligned Elements.
@vishanurag

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by govindbairi** [comment]
This branch has no conflicts with the base branch

**Comment by vishanurag** [comment]
> This branch has no conflicts with the base branch

There are total 16 merge conflicts in this PR. Please resolve them in order to merge

**Comment by govindbairi** [comment]
@vishanurag Sir! latest Code is not Good So,i worked on Previous code

**Comment by vishanurag** [comment]
This PR can't be accepted because the new UI of website is completely different.

**Pull request closed without merging**
