### PR TITLE
changed the about page UI

### PR DESCRIPTION
**Pull request by DevROHIT11**
### Related Issue
Closes: #724

### Description
I was Assigned to the task for doing changes in about-us page , I simply add some more features to UI of that page like by adding horizintal line , png's , aligning the content , etc . By doing this the about us page looks more attractive now!!

## How Has This Been Tested? ⚙️
1.  Changing the source code .
2. Previewing it on chrome browser 
3. Inspecting through chrome.
4. Finalizing the change. 

## Video After Change 📷

https://github.com/user-attachments/assets/64010936-c36b-4f87-b7a3-8171a28a77bc

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [ ] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by DevROHIT11** [comment]
Okk

**Comment by DevROHIT11** [comment]
hello admin !!
I had resolved the merge conflict.

**Comment by vishanurag** [comment]
You need to resolve merge conflicts or you can create a new pr either

**Comment by DevROHIT11** [comment]
How to resolve merge conflicts???

**Comment by vishanurag** [comment]
> How to resolve merge conflicts???

You can simply raise a new pr after making changes in the most updated version of the repo if you don't know how to resolve merge conflicts

**Comment by DevROHIT11** [comment]
@vishanurag i had resolved all the merge conflicts caan u plz accept my pull request

**Comment by vishanurag** [comment]
There are several problems in this PR.
You can check them at: https://deploy-preview-796--tourmaline-bavarois-d21f10.netlify.app/

**Pull request closed without merging**
