### PR TITLE
Changed the Title of this website to make it look more appealing and attractive.

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Added styling to the title which made the website look more of creative side.

Screenshot 2024-10-05 205454

### CODE REVIEW

**Comment by vishanurag** [comment]
Please mention your issue no.

**Comment by NIKITABARANWAL890** [comment]
> Please mention your issue no.

Issue no. #145
I'm always open to suggestions and feedback. If there's anything you'd like me to improve or correct, kindly let me know.

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by NIKITABARANWAL890** [comment]
> Please resolve merge conflicts

I've resolved the merge conflicts in index.html, committed the changes, and pushed the updated branch. Please let me know if further adjustments are needed.

**Pull request closed without merging**
