### PR TITLE
Fixed Header misalignment in contributors page done 🐞🐞🐞! #1271 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Fixed Header misalignment in Contributors page done - #1273

Before -
Screenshot 2024-11-10 020449

Now -
Screenshot 2024-11-10 030201
Screenshot 2024-11-10 030217

### Type of change
What sort of changes have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishanurag

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by Subhajit-2023-44** [comment]
> Please resolve merge conflicts

@vishanurag sir done

**Comment by Subhajit-2023-44** [comment]
@vishanurag

**Pull request merged**
