### PR TITLE
Color palette improved.

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no. #313

hey @vishanurag sir,
so sorry for this late sir.

I've modified the the canvas palette, kindly review once.
Screenshot 2024-10-17 225010

Changes few bugs also,
Before:

https://github.com/user-attachments/assets/b5de2d96-e315-426c-82d6-f677080fac8f

After:

https://github.com/user-attachments/assets/4127434b-c4b6-4afc-a986-bc2bc4858ed9

Changes done:

1.fixed the alignment of the entire home page
2.modified canvas palette
3.adjusted few alignments

Please let me know if any further adjustments are needed.

### CODE REVIEW

**Comment by NIKITABARANWAL890** [comment]
@vishanurag sir kindly review this PR once

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by NIKITABARANWAL890** [comment]
> Please resolve merge conflicts

Done sir

**Comment by NIKITABARANWAL890** [comment]
Hey @vishanurag sir, you assigned me this issue with level 2 but while merging you changed it to level 1. 
Kindly lable it with level2 atleast.

**Pull request merged**
