### PR TITLE
Palette Options Are Not Functional in Canvas Editor

### PR DESCRIPTION
**Pull request by snehhhcodes**
## Title of the Pull Request
 Palette Options were Not Functional in Canvas Editor -FIXED !!

## Related Issue
Closes: #610 

## Description
The palette options in the canvas editor have been successfully fixed, restoring full functionality to essential drawing features. Users can now easily select brush sizes, shapes, colors, and other drawing tools without any issues. This improvement significantly enhances their ability to create and customize their artwork, aligning perfectly with the website's primary goal of providing an effective platform for users to draw.

## How Has This Been Tested? ⚙️

Open the canvas editor on the website.
Access the palette options for brush size, shape, color, and other drawing tools.
Test the selection and application of different options to confirm that they respond correctly.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [X] My code follows the code style of this project.
- [X] I have followed the contribution guidelines
- [X] I have performed a self-review of my own code.
- [X] I have ensured my changes don't generate any new warnings or errors.
- [X] I have updated the documentation (if necessary).
- [X] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@vishanurag been more thn 2 time i made PR for the same please consider it as again n again it will cause merge conflict as chnges are made in index file

**Comment by snehhhcodes** [comment]
add labels and appropriate level too @vishanurag

**Comment by snehhhcodes** [comment]
@vishanurag any update on this?

**Comment by vishanurag** [comment]
See, there are multiple issue with this PR.
Firstly, the cursor effect is gone from all the pages.
Second, the website gone to dark mode and the dark mode toggle button is not working.

If I merge this PR then the above problems will occur.
That's why I am rejecting this PR right now.

**Pull request closed without merging**
