### PR TITLE
feat:Added a footer section in about us page

### PR DESCRIPTION
**Pull request by likitha-kapu**
### Title of the Pull Request
- [x ] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #1160 

### Description

I have added a footer section in the about us page similar to the one existing in the review page.
This enhances navigation and provides essential information about the website, improving user experience and accessibility.

## How Has This Been Tested? ⚙️

I have verified the responsiveness of the options like the quicklinks etc..

## Screenshots 📷

Screenshot 2024-11-03 171349

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [ X] My code follows the code style of this project.
- [X ] I have followed the contribution guidelines
- [X ] I have performed a self-review of my own code.
- [X ] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [ X] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please resolve merge conflicts

**Comment by likitha-kapu** [comment]
@vishanurag Check out once

**Comment by likitha-kapu** [comment]
@vishanurag can you add me a level2,ggsoc24 extend label

**Comment by vishanurag** [comment]
image

image

There is some problem with this PR. I think you made some mistakes while resolving the merge conflict in GitHub.

**Comment by likitha-kapu** [comment]
@vishanurag I will check once

**Pull request closed without merging**
