### PR TITLE
Add support for multiple text elements on canvas #26 UPDATE

### PR DESCRIPTION
**Pull request by Sagar2006**
Fixes: #26 

## UI Changes
- Add a new "Add Text" button next to the existing controls
- Consider renaming the "Save" button to "Update" for clarity

## Benefits
- Users can create more complex designs with multiple text elements
- Increased flexibility and functionality of the text editor
- Improved user experience for creating diverse canvas designs

## Potential Challenges
- Ensuring smooth performance with multiple text elements
- Implementing an intuitive selection mechanism for editing specific text elements
- Updating the undo/redo functionality to work with multiple elements

## Additional Considerations
- We may need to update the drag functionality to work with individual text elements
- The capitalize/lowercase buttons should apply to the selected text element
- Consider adding a way to delete individual text elements

## Next Steps
1. Discuss the proposed changes with the team
2. Create a new branch for this feature
3. Implement the changes and test thoroughly
4. Update documentation to reflect the new functionality
5. Create a pull request for review

Please comment with any suggestions or concerns about this proposed feature.

### CODE REVIEW

**Comment by Sagar2006** [comment]
Kindly check now

**Comment by Sagar2006** [comment]
@vishanurag Please comment with any suggestions or concerns about this proposed feature.

**Comment by vishanurag** [comment]
From next time, please try to mention the issue no. on the top of first comment of pr.

Screenshot_2024-10-02-17-22-33-803_com android chrome-edit

**Comment by Sagar2006** [comment]
Thank you for your guidance over this.

**Comment by vishanurag** [comment]
No problem.

**Pull request merged**
